### PR TITLE
Start using Core Dropdown in Angular and React

### LINKED ISSUE #638: Dropdown: Not compatible with screen reader
When opening a dropdown it's not possible to get the list-box items to be read by screen reader.

### PR DESCRIPTION
**Pull request by splashdust**
This PR swaps out the internals of the Dropdown component in React and Angular with the new Web Component based one from Green Core.

A number of things needs to be done, tested and verified before this PR can be merged, check the associated [milestone](https://github.com/sebgroup/green/milestone/7) for more details.

Closes #638, #667, #700, #779, #863, #696, #600, #862

### CODE REVIEW

**Comment by splashdust** [comment]
Storybook comment action failed, but here are the related Storybooks:

Angular: https://sebgroup.github.io/green/pr-1016/angular/?path=/docs/components-dropdown--custom-option#dropdown
React: https://sebgroup.github.io/green/pr-1016/react/?path=/docs/components-dropdown--dropdown#dropdown

**Comment by splashdust** [comment]
## Green Angular 2.0.0
The two main changes in this version is that the base version of Angular have been updated to 15, and the Dropdown component have been migrated over to the new Web Component powered version from `@sebgroup/green-core`.

### Breaking changes
* Angular updated from 14 -> 15. This means that if your project is still on Angular 14, you will most likely need to upgrade to 15 in order to use this version of Green Angular.
* Any Dropdown related imports that was previously imported from `@sebgroup/extract` will now need to be imported from `@sebgroup/green-angular` instead.
* The `loop` attribute of `ngg-dropdown` no longer has any effect and should no longer be used. This was used configure wether keyboard navigation in the listbox should wrap around when you reach the last option. The motivation for removing the option is that the behaviour should always be the same and not configurable.

## Green React 2.0.0
The main change in this version is that the Dropdown component have been migrated over to the new Web Component powered version from `@sebgroup/green-core`.

### Breaking changes
* Any Dropdown related imports that was previously imported from `@sebgroup/extract` will now need to be imported from `@sebgroup/green-react` instead.
* The `loop` property of `Dropdown` no longer has any effect and should no longer be used. This was used configure wether keyboard navigation in the listbox should wrap around when you reach the last option. The motivation for removing the option is that the behaviour should always be the same and not configurable.

## Extract 2.0.0
The main change in this version is that Dropdown has now been dropped from Extract. The framework independent implementation of Dropdown is now a Web Component in `@sebgroup/green-core` instead.

### Breaking changes
* Dropdown has been dropped from Extract

**Review by vsjolander — APPROVED** [review]
Extensive work!! Very well done 😊  Looks good to me but I also need to get into this lib more and also into webcomponents in general.

I managed to the styles in place - we didn't have designs for listbox or dialog so will have to check this with Jessi.

**Comment by splashdust** [comment]
> I managed to the styles in place - we didn't have designs for listbox or dialog so will have to check this with Jessi.

I believe there are designs for this in Figma, but it's called "Dropdown list" there. The use of `dialog` here is just a semantic choice, and shouldn't really affect styling.

**Pull request merged**
