### PR TITLE
Updated focus states in Chlorophyll

### LINKED ISSUE #981: Focus states: Wrong outline when focusing on buttons and links (probably other elements aswell)
### Does the component already exist

- [X] I confirm that I have checked if the component already exists in any of the Green libraries

### For which framework/library you are requesting the component

Chlorophyll

### Description

The outline styling is not following the style that's defined in DesignLibrary.

### Who will benefit from this feature?

Everyone

### Anything else?

No, not atm.

### PR DESCRIPTION
**Pull request by splashdust**
According to https://designlibrary.sebgroup.com/patterns/pattern-focusstate

image

Closes #981

### CODE REVIEW

**Comment by EldRoos** [comment]
Checking all components:
* Close button - white outline outside the black (I still like it, but it's not following the design).
* Buttons, colored buttons, links, inline links - works perfect.
* Show code button - not changed, still blue on bottom, but is a storybook problem.
* ...

.. will continue checking components soon...

**Comment by splashdust** [comment]
@EldRoos Thank you for the thorough review! Apparently the Storybook deploy wasn't triggered for my last push to this PR, which contained a fix for the close button. I manually triggered it now, so now the close button outline should match the rest!

**Comment by EldRoos** [comment]
* Close button - works perfectly.
* Text area, stepper - works perfectly.
* Disabled - still can be focused?
* Datepicker, dropdown - looks good but hard to test fully without js.
* Filter chip, icons, modal, slide toggle, in page wizard - works perfectly.
* Links with icon - full line focus, correct?
* Slider - works good, buy maybe have bigger press area? (but not problem with focus)
* Table sort, table checkboxes - works perfectly.
* Tabs -. works perfectly - looks great!

Checked near 100%. Most things are very good. Just a few questions about icon links & disabled?

**Review by vsjolander — APPROVED** [review]
Looks very good to me! Components work great, nice cleanup in code 👍

**Pull request merged**
