### PR TITLE
refactor: 💡 React Flexbox component

### PR DESCRIPTION
**Pull request by terrance456**
screencapture-localhost-4200-2022-03-08-16_24_27

### CODE REVIEW

**Comment by sebopensource** [comment]
👋 Thanks for creating a pull request! 🚀 Checkout the storybook we've created for it: <ul><li><a target="_blank" href="https://sebgroup.github.io/green/pr-432/react/">react</a></li></ul>

**Comment by terrance456** [comment]
https://sebgroup.github.io/green/pr-432/react/?path=/docs/components-layout-flexbox--flexbox

**Review by hjalmers — APPROVED** [review]
Have you thought about adding the ability to use different breakpoints as well? Eg. `justify-content-lg-end` to alter flexbox behaviour on certain breakpoints? See https://getbootstrap.com/docs/5.0/utilities/flex/ for more options and examples.

**Comment by terrance456** [comment]
> Have you thought about adding the ability to use different breakpoints as well? Eg. `justify-content-lg-end` to alter flexbox behaviour on certain breakpoints? See https://getbootstrap.com/docs/5.0/utilities/flex/ for more options and examples.

Yeah was thinking about it, will add that in as well

**Pull request merged**
