### PR TITLE
feat: adding pagination component

### LINKED ISSUE #788: Pagination component
### Does the component already exist

- [X] I confirm that I have checked if the component already exists in any of the Green libraries

### For which framework/library you are requesting the component

Chlorophyll

### Description

Pagination for tables or lists

### Who will benefit from this feature?

Everyone who needs to display multiple pages of data

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by R0tenur**
Should resolve #788

### CODE REVIEW

**Comment by vsjolander** [comment]
@R0tenur thank's a bunch for contributing!

We have an open PR for this component that's being worked on by @Maximilian-R maybe you two could sync your work?

**Comment by Maximilian-R** [comment]
Hi @R0tenur, can you check if this PR includes the same functionality you have added here? :) https://github.com/sebgroup/green/pull/735

If so, I can merge it now and finish the remaining angular issues in a new branch (the chlorophyll part is done)

**Comment by R0tenur** [comment]
I donat care about my code, that is copied from our application. Just want it to be in green so we don't Neeson to manage thw CSS there

**Comment by Maximilian-R** [comment]
Well, you can still check if the css matches? I am asking if there is anything from this PR that we should carry over to the other one

**Comment by Maximilian-R** [comment]
https://github.com/sebgroup/green/pull/735 was merged

**Comment by R0tenur** [comment]
Nice! Then we can refactor this code away from our application

**Pull request closed without merging**
