### PR TITLE
Fix/in wizard

### PR DESCRIPTION
**Pull request by sjkayle**
Changes include -

- use correct font-weight keyword for strong tag/class (semibold is invalid)
- update documentation for in-page wizard summary step to make subtitle bold as per design library guidelines

### Preview

image

### CODE REVIEW

**Review by mario-subo — APPROVED** [review]

**Review by vsjolander — COMMENTED** [review]
Thanks for the PR! 

I'm not sure about this though. We did change the style of headers which changes this design since we use a `h4` in the example. 

Adding a `.strong` class is more of a typography feature that might be needed but I think we neeed to think more about these utility classes.

I think changing the content of this wizard example to a [value list component](https://sebgroup.github.io/green/latest/chlorophyll/?path=/docs/components-list--page#value-list) would be better. We did have a inverted variant of that component that is exactly what we were looking for but [it was removed](https://github.com/sebgroup/green/commit/d36caac913986b3f66084707e3697ef8070cacc6). It [exsists in Figma](https://www.figma.com/file/dX0HJ2MOaQyAOTziCD5fQ7/SEB-Design-System?type=design&node-id=14694-51365&mode=design) but it lives in a weird place (Inputs?).

We should probably move the Figma component to lists and call it value list with the variant of inverted or smth and reimplement the css and change the content of this wizard example or skip this all together... not sure..

What do you guys think @splashdust @astrit?

**Comment by sjkayle** [comment]
@vsjolander using a value list seems like a good idea

**Review by splashdust — APPROVED** [review]
👍

**Comment by splashdust** [comment]
@vsjolander @sjkayle Didn't notice the comments until after I had left review, but yes, I agree on changing it to a value list!

**Comment by sjkayle** [comment]
@vsjolander @splashdust I've pushed a commit and used value lists in the documentation as suggested. Kindly review again.

image

**Review by splashdust — APPROVED** [review]
Great!

Also, I didn't notice the addition of `.strong` at first, but I removed it now. There is already a utility class called `.fw-bold` that can be used to change font-weight. So if you need bold text without *strong* semantics, that's the one you should use.

**Pull request merged**
