### PR TITLE
feat: 🎸 add badge component with tests

### PR DESCRIPTION
**Pull request by ethan-qsh**
image

### CODE REVIEW

**Comment by ethan-qsh** [comment]
There is a style issue with the badge spanning the whole width when it is a singular badge. Is it intended or does that need to fix? @hjalmers

**Comment by sebopensource** [comment]
👋 Thanks for creating a pull request! 🚀 Checkout the storybook we've created for it: <ul><li><a target="_blank" href="https://sebgroup.github.io/green/pr-443/react/">react</a></li></ul>

**Comment by hjalmers** [comment]
@ethan-qsh I'll look into it and let you know:)

**Comment by JohanObrink** [comment]
@hjalmers When you have had a look at the spanning issue, you can undraft the PR again :)

**Pull request merged**
