### PR TITLE
chore: 🤖 migrating NX and Storybook to newer versions

### PR DESCRIPTION
**Pull request by vsjolander**
Never done migrations of these before but it seems to work on my machine.

Reviews would be much appreciated 👍 

Not sure if we need to migrate, but we ran in to many errors during a mob programming with developers from SEB and to remove some of them we needed to update packages.

Not all warnings are fixed and I will test this branch on my PC to see if it gets stuck.

We need to make it easier to contribute because now you can't even get past yarn/npm on a windows machine.

### CODE REVIEW

**Comment by vsjolander** [comment]
Hopefully closes #651

**Comment by Maximilian-R** [comment]
installation was successful from windows pc with npm install and build:all seems to work fine 👍

It keeps complaining about this though: 

```
 >  NX   Nx Cloud Problems
   - Request failed with status code 400. Your request could not be processed. Request could not be handled
```

Just me or for you as well?

**Comment by splashdust** [comment]
From a clean slate I still get some issues on my SEB machine, there's a conflict with `rxjs`. Gonna try upgrading it.

**Comment by splashdust** [comment]
This PR is superseded by #801

**Pull request closed without merging**
