### PR TITLE
Use case: Lighthouse 1

### PR DESCRIPTION
**Pull request by JohanObrink**
#249

### CODE REVIEW

**Comment by sebopensource** [comment]
👋 Thanks for creating a pull request! 🚀 Checkout the storybook we created for it [here](https://sebgroup.github.io/green/pr-250/chlorophyll/).

**Comment by hjalmers** [comment]
Is this ready for review and can we merge this now @JohanObrink or do you want to add/fix something more first? Once this is merged into main I planed on doing a new alpha release.

**Pull request merged**
