### PR TITLE
feat(in-page-wizard): add markup examples for In-page wizard

### PR DESCRIPTION
**Pull request by splashdust**
# In-page wizard
This PR contains markup examples for the In-page wizard component in Chlorophyll. The examples are based on the current specification in Design Library: https://designlibrary.sebgroup.com/components/component-inpagewizard

### CODE REVIEW

**Comment by sebopensource** [comment]
👋 Thanks for creating a pull request! 🚀 Checkout the storybook we've created for it: <ul><li><a target="_blank" href="https://sebgroup.github.io/green/pr-823/chlorophyll/">chlorophyll</a></li></ul>

**Comment by vsjolander** [comment]
Looks good!

I have built a version of this with the consumer team and should add it to the repo before parental leave 🙈

**Comment by splashdust** [comment]
@vsjolander Oh, cool! Can you add the code you have so far to this draft PR?

**Comment by vsjolander** [comment]
> @vsjolander Oh, cool! Can you add the code you have so far to this draft PR?

@splashdust I've now added SCSS and markup (somewhat tweaked from what was created in Consumer Loans app...)!

**Comment by splashdust** [comment]
@vsjolander Awesome, thank you!

**Pull request merged**
