### PR TITLE
Feat/dropdown

### PR DESCRIPTION
**Pull request by Maximilian-R**
Add support without angular forms and update examples
Fix selected: bool in option ?

### CODE REVIEW

**Comment by JohanObrink** [comment]
@Maximilian-R and @hjalmers I tried to rebase/merge in main and test this branch to start a discussion. It b0rked totally though. It seems changes have been made in main that conflict.

Can you guys strike up a conversation on the things this branch should accomplish so that it can move forward?

**Comment by Maximilian-R** [comment]
> up a conversation on the things this branch should accomplish so that it can move forward?

Hmm, I don't get any conflict when rebasing from main on this branch. The build fails of some changes in the angular-storybook, haven't had time to complete that.

The goal of this branch is to make the angular-dropdown usable without Angular Forms - with updated docs how to use it with and without

**Comment by hjalmers** [comment]
@Maximilian-R let me know if you need any help or input:)

**Comment by Maximilian-R** [comment]
> d any help or input:)

Sure that would be great :) Trying to provide a custom docs page (mdx) for the angular dropdown story, perhaps I'm missing some configuration for this to work properly?

**Comment by hjalmers** [comment]
@Maximilian-R feel free to add and improve the docs:) We should probably add something about how to set initial value at least...

**Comment by hjalmers** [comment]
You can view the updated storybook [here](https://sebgroup.github.io/green/pr-398/angular/?path=/docs/components-dropdown--select).

**Comment by Maximilian-R** [comment]
Awesome! 👏 Will add some docs

**Pull request merged**
