### PR TITLE
refactor: 💡 alert component storybook

### PR DESCRIPTION
**Pull request by ethan-qsh**

### CODE REVIEW

**Comment by sebopensource** [comment]
👋 Thanks for creating a pull request! 🚀 Checkout the storybook we created for it [here](https://sebgroup.github.io/green/pr-337/chlorophyll/).

**Comment by ethan-qsh** [comment]
You can preview the storybook changes here:
https://sebgroup.github.io/green/pr-337/react/?path=/docs/components-alert--alert

**Comment by ethan-qsh** [comment]
I noticed that the alert component places the button with weird spacing. There may need to be some changes to the styles to correct that. 

image

**Review by hjalmers — CHANGES_REQUESTED** [review]
I guess you've been looking at the latest available example of the alert deployed on github and not in the repo (I'll try to deploy a new version soon). In any case, here's how they should look when correct markup is used:  

image

And here's the markup:
```html
<div role="alert" class="info">
      <header>
        <h3>Heading</h3>
        <button class="close"><span class="sr-only">Close</span></button>
      </header>
      <p>
        Alert content placed inside a paragraph. Inline <a href="#">links</a> will inherit color from alert to make sure contrast is okay.
      </p>
      <footer>
        <button type="button">Default button</button>
        <button type="button" class="primary">Primary button</button>
      </footer>
    </div>
    <div role="alert" class="success">
      <header>
        <h3>Heading</h3>
        <button class="close"><span class="sr-only">Close</span></button>
      </header>
      <p>
        Alert content placed inside a paragraph. Inline <a href="#">links</a> will inherit color from alert to make sure contrast is okay.
      </p>
      <footer>
        <button>Default button</button>
        <button class="primary">Primary button</button>
      </footer>
    </div>
    <div role="alert" class="warning">
      <header>
        <h3>Heading</h3>
        <button class="close"><span class="sr-only">Close</span></button>
      </header>
      <p>
        Alert content placed inside a paragraph. Inline <a href="#">links</a> will inherit color from alert to make sure contrast is okay.
      </p>
      <footer>
        <button>Default button</button>
        <button class="primary">Primary button</button>
      </footer>
    </div>
    <div role="alert" class="danger">
      <header>
        <h3>Heading</h3>
        <button class="close"><span class="sr-only">Close</span></button>
      </header>
      <p>
        Alert content placed inside a paragraph. Inline <a href="#">links</a> will inherit color from alert to make sure contrast is okay.
      </p>
      <footer>
        <button>Default button</button>
        <button class="primary">Primary button</button>
      </footer>
</div>
```

I.e. when close button is added it should be added within a header element together with the heading. Buttons should also be added to a footer element (even if it's just a single button).

**Review by hjalmers — APPROVED** [review]

**Pull request merged**
