### PR TITLE
Feat/pagination

### PR DESCRIPTION
**Pull request by Maximilian-R**
Paginaton component

### CODE REVIEW

**Comment by Maximilian-R** [comment]
Booked green coaching for remaining issues

- [ ] Static translations in a component (eg. Goto Page, Goto Last, Goto First)
- [ ] Global styles for a, ul etc conflicts with the pagination elements
- [ ] Replace svg icons with fontawesome pro regular (currently using free solid)

**Comment by sebopensource** [comment]
👋 Thanks for creating a pull request! 🚀 Checkout the storybooks we've created for it: <ul><li><a target="_blank" href="https://sebgroup.github.io/green/pr-735/chlorophyll/">chlorophyll</a></li><li><a target="_blank" href="https://sebgroup.github.io/green/pr-735/angular/">angular</a></li></ul>

**Comment by Maximilian-R** [comment]
Do not merge, will add some tests! :)

**Review by vsjolander — COMMENTED** [review]
Awesome work!

Tested it out and noticed some issues:

### Issue 1
When on page 1 and clicking on next arrow, the prev-arrow is added and push the buttons so if I click again w/o moving mouse I go to last page.

Screenshot 2023-03-02 at 12 39 04

Screenshot 2023-03-02 at 12 39 08

Maybe arrows should always keep it's space? 

The dots are also changing right arrow position, but maybe not a problem.

### Issue 2

Doesn't seem to work with keyboard navigation (Enter or Space) to select pages or prev/next

**Comment by Maximilian-R** [comment]
@vsjolander Excellent feedback, will look into it! 👷

**Comment by Maximilian-R** [comment]
fix remaining changes in #790

**Pull request merged**
