### PR TITLE
refactor: 💡 card storybook

### PR DESCRIPTION
**Pull request by ethan-qsh**

### CODE REVIEW

**Comment by sebopensource** [comment]
👋 Thanks for creating a pull request! 🚀 Checkout the storybook we created for it [here](https://sebgroup.github.io/green/pr-341/chlorophyll/).

**Comment by ethan-qsh** [comment]
We added a new option in storybook (as shown below) to display the props of the component in a table for the user to preview. What are your thoughts on having this? @JohanObrink @hjalmers

image

You can preview the storybook in this link
https://sebgroup.github.io/green/pr-341/react/?path=/docs/components-card--card

**Comment by terrance456** [comment]
Does the min-height of the card suppose to be like above when its place to each other where the first card has only headline and second card has plain text in the card-body ? @hjalmers @JohanObrink

**Comment by terrance456** [comment]
It has some spacing issue when button are being passed in card, is it a chlorophyll styling fix?  or we can just pass in bootstrap grid in the component to space it out by default ?

**Review by hjalmers — CHANGES_REQUESTED** [review]
Same as my comment regarding alerts, the latest version available in the repo has slightly different markup and uses the same principle as for alerts.

image

Markup:
```html
<section class="card">
      <header>
        <h3>Heading</h3>
        <button class="close"><span class="sr-only">Close</span></button>
      </header>
      <p>
        Card content placed here.
      </p>
      <footer>
        <a href="#" class="button link">Link</a>
        <button type="button">Default button</button>
        <button type="button" class="primary">Primary button</button>
      </footer>
    </section>
```

I.e. heading in header element, buttons and links in footer (unless inline links in content), no class for card content/body .

**Review by terrance456 — APPROVED** [review]

**Review by hjalmers — APPROVED** [review]

**Pull request merged**
